### 作業目的: 更加了解word2vec高速化
本次作業主要是幫同學更熟悉與了解各項技巧來加速word2vec的原理，同學可以參考章節講義來回答下列問題。

### Q1 - 請問word2vec原本的設計有何問題以及可以怎麼對相對應的問題做改善?

Answer:
- **Problem**:
    - For each training sample, **only the weights corresponding to the target word might get a significant update**. While training a neural network model, in each back-propagation pass we try to update all the weights in the hidden layer. The weight corresponding to non-target words would receive a marginal or no change at all, i.e. in each pass we only make very sparse updates.
    - For every training sample, **the calculation of the final probabilities using the softmax is quite an expensive operation** as it involves a summation of scores over all the words in our vocabulary for normalizing.
- **Solution**:
    - Hierarchical Softmax
    - Negative Sampling

### Q2 - 請問在Negative Sampling中的次方係數，會如何影響字詞的抽取?
Hint: 如何影響高頻詞與低頻詞的抽取機率

Answer:<br>
The 3/4 power makes **less frequent words be sampled more often**, without it probability of sampling frequent words such as “the”, “is” etc would be much higher than words like “zebra”, “elephant” etc.

In [1]:
import numpy as np

freq = [15, 10, 2]
factors = [1.0, 0.75, 0.5]
for factor in factors:
    numerator = np.power(freq, factor)
    denominator = np.sum(numerator)
    print(numerator / denominator)

[0.55555556 0.37037037 0.07407407]
[0.51061101 0.37672265 0.11266635]
[0.45836973 0.37425731 0.16737296]


### Reference:
- [Word2Vec Tutorial Part 2 - Negative Sampling](http://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/)
- [NLP 102: Negative Sampling and GloVe](http://mccormickml.com/2017/01/11/word2vec-tutorial-part-2-negative-sampling/)